# Generated by Django 5.0 on 2024-01-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'portfolio'},
        ),
    ]
